id = "revibe"
name = "REVIBE"
description = "Mistral's open-source coding assistant"
version = "1.3.0"
schema_version = 1
authors = ["Mistral AI"]
repository = "https://github.com/revibe-ai/revibe"

[agent_servers.revibe]
name = "REVIBE"
icon = "./icons/revibe.svg"

[agent_servers.mistral-vibe.targets.darwin-aarch64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-darwin-aarch64-1.3.0.zip"
cmd = "./vibe-acp"

[agent_servers.mistral-vibe.targets.darwin-x86_64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-darwin-x86_64-1.3.0.zip"
cmd = "./vibe-acp"

[agent_servers.mistral-vibe.targets.linux-aarch64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-linux-aarch64-1.3.0.zip"
cmd = "./vibe-acp"

[agent_servers.mistral-vibe.targets.linux-x86_64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-linux-x86_64-1.3.0.zip"
cmd = "./vibe-acp"

[agent_servers.mistral-vibe.targets.windows-aarch64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-windows-aarch64-1.3.0.zip"
cmd = "./vibe-acp.exe"

[agent_servers.mistral-vibe.targets.windows-x86_64]
archive = "https://github.com/revibe-ai/revibe/releases/download/v1.3.0/vibe-acp-windows-x86_64-1.3.0.zip"
cmd = "./vibe-acp.exe"
